/* *
                      _
  ___   _   _   ___  | |_    ___    _ __ ___
 / __| | | | | / __| | __|  / _ \  | '_ ` _ \
| (__  | |_| | \__ \ | |_  | (_) | | | | | | |
 \___|  \__,_| |___/  \__|  \___/  |_| |_| |_|

*/
// * Code generated by protoc-gen-custom. DO NOT EDIT.
// * versions:
// * - protoc-gen-custom (devel)
// * - protoc                   v3.14.0
// * source: pb

package product

const (
	ProductService_RetrieveProductByID = "/pb.ProductService/RetrieveProductByID"
	ProductService_ListProduct         = "/pb.ProductService/ListProduct"
	ProductService_CreateProduct       = "/pb.ProductService/CreateProduct"
	ProductService_UpdateProductByID   = "/pb.ProductService/UpdateProductByID"
	ProductService_DeleteProductByID   = "/pb.ProductService/DeleteProductByID"
	ProductService_DeleteProductByIDs  = "/pb.ProductService/DeleteProductByIDs"
	ProductService_PurchaseProduct     = "/pb.ProductService/PurchaseProduct"
)
