// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: forgot_password.proto

package common

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type ForgotPassword struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserName   string `protobuf:"bytes,1,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	Name       string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email      string `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	ResetToken string `protobuf:"bytes,4,opt,name=reset_token,json=resetToken,proto3" json:"reset_token,omitempty"`
}

func (x *ForgotPassword) Reset() {
	*x = ForgotPassword{}
	if protoimpl.UnsafeEnabled {
		mi := &file_forgot_password_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ForgotPassword) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForgotPassword) ProtoMessage() {}

func (x *ForgotPassword) ProtoReflect() protoreflect.Message {
	mi := &file_forgot_password_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForgotPassword.ProtoReflect.Descriptor instead.
func (*ForgotPassword) Descriptor() ([]byte, []int) {
	return file_forgot_password_proto_rawDescGZIP(), []int{0}
}

func (x *ForgotPassword) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *ForgotPassword) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ForgotPassword) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *ForgotPassword) GetResetToken() string {
	if x != nil {
		return x.ResetToken
	}
	return ""
}

var File_forgot_password_proto protoreflect.FileDescriptor

var file_forgot_password_proto_rawDesc = []byte{
	0x0a, 0x15, 0x66, 0x6f, 0x72, 0x67, 0x6f, 0x74, 0x5f, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72,
	0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x78, 0x0a, 0x0e, 0x46,
	0x6f, 0x72, 0x67, 0x6f, 0x74, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x1b, 0x0a,
	0x09, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14,
	0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65,
	0x6d, 0x61, 0x69, 0x6c, 0x12, 0x1f, 0x0a, 0x0b, 0x72, 0x65, 0x73, 0x65, 0x74, 0x5f, 0x74, 0x6f,
	0x6b, 0x65, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x72, 0x65, 0x73, 0x65, 0x74,
	0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x42, 0x0c, 0x5a, 0x0a, 0x6d, 0x73, 0x67, 0x2f, 0x63, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_forgot_password_proto_rawDescOnce sync.Once
	file_forgot_password_proto_rawDescData = file_forgot_password_proto_rawDesc
)

func file_forgot_password_proto_rawDescGZIP() []byte {
	file_forgot_password_proto_rawDescOnce.Do(func() {
		file_forgot_password_proto_rawDescData = protoimpl.X.CompressGZIP(file_forgot_password_proto_rawDescData)
	})
	return file_forgot_password_proto_rawDescData
}

var file_forgot_password_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_forgot_password_proto_goTypes = []interface{}{
	(*ForgotPassword)(nil), // 0: pb.ForgotPassword
}
var file_forgot_password_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_forgot_password_proto_init() }
func file_forgot_password_proto_init() {
	if File_forgot_password_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_forgot_password_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ForgotPassword); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_forgot_password_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_forgot_password_proto_goTypes,
		DependencyIndexes: file_forgot_password_proto_depIdxs,
		MessageInfos:      file_forgot_password_proto_msgTypes,
	}.Build()
	File_forgot_password_proto = out.File
	file_forgot_password_proto_rawDesc = nil
	file_forgot_password_proto_goTypes = nil
	file_forgot_password_proto_depIdxs = nil
}
