// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: forgot_password.proto

package common

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on ForgotPassword with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *ForgotPassword) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ForgotPassword with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in ForgotPasswordMultiError,
// or nil if none found.
func (m *ForgotPassword) ValidateAll() error {
	return m.validate(true)
}

func (m *ForgotPassword) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for UserName

	// no validation rules for Name

	// no validation rules for Email

	// no validation rules for ResetToken

	if len(errors) > 0 {
		return ForgotPasswordMultiError(errors)
	}

	return nil
}

// ForgotPasswordMultiError is an error wrapping multiple validation errors
// returned by ForgotPassword.ValidateAll() if the designated constraints
// aren't met.
type ForgotPasswordMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ForgotPasswordMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ForgotPasswordMultiError) AllErrors() []error { return m }

// ForgotPasswordValidationError is the validation error returned by
// ForgotPassword.Validate if the designated constraints aren't met.
type ForgotPasswordValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ForgotPasswordValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ForgotPasswordValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ForgotPasswordValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ForgotPasswordValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ForgotPasswordValidationError) ErrorName() string { return "ForgotPasswordValidationError" }

// Error satisfies the builtin error interface
func (e ForgotPasswordValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sForgotPassword.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ForgotPasswordValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ForgotPasswordValidationError{}
