// Code generated by mockery v2.39.1. DO NOT EDIT.

package mocks

import (
	time "time"

	mock "github.com/stretchr/testify/mock"
)

// Claims is an autogenerated mock type for the Claims type
type Claims struct {
	mock.Mock
}

// AddExpired provides a mock function with given fields: _a0
func (_m *Claims) AddExpired(_a0 time.Duration) {
	_m.Called(_a0)
}

// Valid provides a mock function with given fields:
func (_m *Claims) Valid() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Valid")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewClaims creates a new instance of Claims. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClaims(t interface {
	mock.TestingT
	Cleanup(func())
}) *Claims {
	mock := &Claims{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
