// Code generated by mockery v2.39.1. DO NOT EDIT.

package mocks

import (
	context "context"
	entity "trintech/review/internal/coupon-management/entity"
	database "trintech/review/pkg/database"

	mock "github.com/stretchr/testify/mock"
)

// CouponRepository is an autogenerated mock type for the CouponRepository type
type CouponRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, db, data
func (_m *CouponRepository) Create(ctx context.Context, db database.Executor, data *entity.Coupon) (int64, error) {
	ret := _m.Called(ctx, db, data)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, database.Executor, *entity.Coupon) (int64, error)); ok {
		return rf(ctx, db, data)
	}
	if rf, ok := ret.Get(0).(func(context.Context, database.Executor, *entity.Coupon) int64); ok {
		r0 = rf(ctx, db, data)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, database.Executor, *entity.Coupon) error); ok {
		r1 = rf(ctx, db, data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteByID provides a mock function with given fields: ctx, db, id
func (_m *CouponRepository) DeleteByID(ctx context.Context, db database.Executor, id int64) error {
	ret := _m.Called(ctx, db, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, database.Executor, int64) error); ok {
		r0 = rf(ctx, db, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RetrieveByCode provides a mock function with given fields: ctx, db, code
func (_m *CouponRepository) RetrieveByCode(ctx context.Context, db database.Executor, code string) (*entity.Coupon, error) {
	ret := _m.Called(ctx, db, code)

	if len(ret) == 0 {
		panic("no return value specified for RetrieveByCode")
	}

	var r0 *entity.Coupon
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, database.Executor, string) (*entity.Coupon, error)); ok {
		return rf(ctx, db, code)
	}
	if rf, ok := ret.Get(0).(func(context.Context, database.Executor, string) *entity.Coupon); ok {
		r0 = rf(ctx, db, code)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Coupon)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, database.Executor, string) error); ok {
		r1 = rf(ctx, db, code)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewCouponRepository creates a new instance of CouponRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCouponRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *CouponRepository {
	mock := &CouponRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
