// Code generated by mockery v2.39.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// isCreateCouponRequest_ApplyId is an autogenerated mock type for the isCreateCouponRequest_ApplyId type
type isCreateCouponRequest_ApplyId struct {
	mock.Mock
}

// isCreateCouponRequest_ApplyId provides a mock function with given fields:
func (_m *isCreateCouponRequest_ApplyId) isCreateCouponRequest_ApplyId() {
	_m.Called()
}

// newIsCreateCouponRequest_ApplyId creates a new instance of isCreateCouponRequest_ApplyId. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newIsCreateCouponRequest_ApplyId(t interface {
	mock.TestingT
	Cleanup(func())
}) *isCreateCouponRequest_ApplyId {
	mock := &isCreateCouponRequest_ApplyId{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
