// Code generated by mockery v2.39.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// isUploadRequest_Data is an autogenerated mock type for the isUploadRequest_Data type
type isUploadRequest_Data struct {
	mock.Mock
}

// isUploadRequest_Data provides a mock function with given fields:
func (_m *isUploadRequest_Data) isUploadRequest_Data() {
	_m.Called()
}

// newIsUploadRequest_Data creates a new instance of isUploadRequest_Data. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newIsUploadRequest_Data(t interface {
	mock.TestingT
	Cleanup(func())
}) *isUploadRequest_Data {
	mock := &isUploadRequest_Data{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
