// Code generated by mockery v2.39.1. DO NOT EDIT.

package mocks

import (
	context "context"
	entity "trintech/review/internal/user-management/entity"
	database "trintech/review/pkg/database"

	mock "github.com/stretchr/testify/mock"
)

// LoginHistoryRepo is an autogenerated mock type for the LoginHistoryRepo type
type LoginHistoryRepo struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, db, data
func (_m *LoginHistoryRepo) Create(ctx context.Context, db database.Executor, data *entity.LoginHistory) (int64, error) {
	ret := _m.Called(ctx, db, data)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, database.Executor, *entity.LoginHistory) (int64, error)); ok {
		return rf(ctx, db, data)
	}
	if rf, ok := ret.Get(0).(func(context.Context, database.Executor, *entity.LoginHistory) int64); ok {
		r0 = rf(ctx, db, data)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, database.Executor, *entity.LoginHistory) error); ok {
		r1 = rf(ctx, db, data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewLoginHistoryRepo creates a new instance of LoginHistoryRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLoginHistoryRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *LoginHistoryRepo {
	mock := &LoginHistoryRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
