// Code generated by mockery v2.39.1. DO NOT EDIT.

package mocks

import (
	context "context"
	entity "trintech/review/internal/user-management/entity"
	database "trintech/review/pkg/database"

	mock "github.com/stretchr/testify/mock"
)

// LoginHistoryRepository is an autogenerated mock type for the LoginHistoryRepository type
type LoginHistoryRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, db, data
func (_m *LoginHistoryRepository) Create(ctx context.Context, db database.Executor, data *entity.LoginHistory) error {
	ret := _m.Called(ctx, db, data)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, database.Executor, *entity.LoginHistory) error); ok {
		r0 = rf(ctx, db, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateLogout provides a mock function with given fields: ctx, db, accessToken
func (_m *LoginHistoryRepository) UpdateLogout(ctx context.Context, db database.Executor, accessToken string) error {
	ret := _m.Called(ctx, db, accessToken)

	if len(ret) == 0 {
		panic("no return value specified for UpdateLogout")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, database.Executor, string) error); ok {
		r0 = rf(ctx, db, accessToken)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewLoginHistoryRepository creates a new instance of LoginHistoryRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLoginHistoryRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *LoginHistoryRepository {
	mock := &LoginHistoryRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
