// Code generated by mockery v2.39.1. DO NOT EDIT.

package mocks

import (
	context "context"
	http "net/http"

	metadata "google.golang.org/grpc/metadata"

	mock "github.com/stretchr/testify/mock"
)

// mapMetaDataFunc is an autogenerated mock type for the mapMetaDataFunc type
type mapMetaDataFunc struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0, _a1
func (_m *mapMetaDataFunc) Execute(_a0 context.Context, _a1 *http.Request) metadata.MD {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 metadata.MD
	if rf, ok := ret.Get(0).(func(context.Context, *http.Request) metadata.MD); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(metadata.MD)
		}
	}

	return r0
}

// newMapMetaDataFunc creates a new instance of mapMetaDataFunc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMapMetaDataFunc(t interface {
	mock.TestingT
	Cleanup(func())
}) *mapMetaDataFunc {
	mock := &mapMetaDataFunc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
