// Code generated by mockery v2.39.1. DO NOT EDIT.

package mocks

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// middlewareFunc is an autogenerated mock type for the middlewareFunc type
type middlewareFunc struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0
func (_m *middlewareFunc) Execute(_a0 http.Handler) http.Handler {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 http.Handler
	if rf, ok := ret.Get(0).(func(http.Handler) http.Handler); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(http.Handler)
		}
	}

	return r0
}

// newMiddlewareFunc creates a new instance of middlewareFunc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMiddlewareFunc(t interface {
	mock.TestingT
	Cleanup(func())
}) *middlewareFunc {
	mock := &middlewareFunc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
