// Code generated by mockery v2.39.1. DO NOT EDIT.

package mocks

import (
	context "context"

	grpc "google.golang.org/grpc"

	mock "github.com/stretchr/testify/mock"

	product "trintech/review/dto/product-management/product"
)

// ProductServiceClient is an autogenerated mock type for the ProductServiceClient type
type ProductServiceClient struct {
	mock.Mock
}

// CreateProduct provides a mock function with given fields: ctx, in, opts
func (_m *ProductServiceClient) CreateProduct(ctx context.Context, in *product.CreateProductRequest, opts ...grpc.CallOption) (*product.CreateProductResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for CreateProduct")
	}

	var r0 *product.CreateProductResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *product.CreateProductRequest, ...grpc.CallOption) (*product.CreateProductResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *product.CreateProductRequest, ...grpc.CallOption) *product.CreateProductResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*product.CreateProductResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *product.CreateProductRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteProductByID provides a mock function with given fields: ctx, in, opts
func (_m *ProductServiceClient) DeleteProductByID(ctx context.Context, in *product.DeleteProductByIDRequest, opts ...grpc.CallOption) (*product.DeleteProductByIDResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for DeleteProductByID")
	}

	var r0 *product.DeleteProductByIDResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *product.DeleteProductByIDRequest, ...grpc.CallOption) (*product.DeleteProductByIDResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *product.DeleteProductByIDRequest, ...grpc.CallOption) *product.DeleteProductByIDResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*product.DeleteProductByIDResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *product.DeleteProductByIDRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteProductByIDs provides a mock function with given fields: ctx, in, opts
func (_m *ProductServiceClient) DeleteProductByIDs(ctx context.Context, in *product.DeleteProductByIDsRequest, opts ...grpc.CallOption) (*product.DeleteProductByIDsResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for DeleteProductByIDs")
	}

	var r0 *product.DeleteProductByIDsResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *product.DeleteProductByIDsRequest, ...grpc.CallOption) (*product.DeleteProductByIDsResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *product.DeleteProductByIDsRequest, ...grpc.CallOption) *product.DeleteProductByIDsResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*product.DeleteProductByIDsResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *product.DeleteProductByIDsRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListProduct provides a mock function with given fields: ctx, in, opts
func (_m *ProductServiceClient) ListProduct(ctx context.Context, in *product.ListProductRequest, opts ...grpc.CallOption) (*product.ListProductResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ListProduct")
	}

	var r0 *product.ListProductResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *product.ListProductRequest, ...grpc.CallOption) (*product.ListProductResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *product.ListProductRequest, ...grpc.CallOption) *product.ListProductResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*product.ListProductResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *product.ListProductRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RetrieveProductByID provides a mock function with given fields: ctx, in, opts
func (_m *ProductServiceClient) RetrieveProductByID(ctx context.Context, in *product.RetrieveProductByIDRequest, opts ...grpc.CallOption) (*product.RetrieveProductByIDResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for RetrieveProductByID")
	}

	var r0 *product.RetrieveProductByIDResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *product.RetrieveProductByIDRequest, ...grpc.CallOption) (*product.RetrieveProductByIDResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *product.RetrieveProductByIDRequest, ...grpc.CallOption) *product.RetrieveProductByIDResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*product.RetrieveProductByIDResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *product.RetrieveProductByIDRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateProductByID provides a mock function with given fields: ctx, in, opts
func (_m *ProductServiceClient) UpdateProductByID(ctx context.Context, in *product.UpdateProductByIDRequest, opts ...grpc.CallOption) (*product.UpdateProductByIDResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for UpdateProductByID")
	}

	var r0 *product.UpdateProductByIDResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *product.UpdateProductByIDRequest, ...grpc.CallOption) (*product.UpdateProductByIDResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *product.UpdateProductByIDRequest, ...grpc.CallOption) *product.UpdateProductByIDResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*product.UpdateProductByIDResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *product.UpdateProductByIDRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewProductServiceClient creates a new instance of ProductServiceClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProductServiceClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *ProductServiceClient {
	mock := &ProductServiceClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
