// Code generated by mockery v2.39.1. DO NOT EDIT.

package mocks

import (
	context "context"
	io "io"

	mock "github.com/stretchr/testify/mock"
)

// Storage is an autogenerated mock type for the Storage type
type Storage struct {
	mock.Mock
}

// UploadObject provides a mock function with given fields: ctx, name, data
func (_m *Storage) UploadObject(ctx context.Context, name string, data io.Reader) (string, error) {
	ret := _m.Called(ctx, name, data)

	if len(ret) == 0 {
		panic("no return value specified for UploadObject")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, io.Reader) (string, error)); ok {
		return rf(ctx, name, data)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, io.Reader) string); ok {
		r0 = rf(ctx, name, data)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, io.Reader) error); ok {
		r1 = rf(ctx, name, data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewStorage creates a new instance of Storage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *Storage {
	mock := &Storage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
