// Code generated by mockery v2.39.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// UnsafeUploadServiceServer is an autogenerated mock type for the UnsafeUploadServiceServer type
type UnsafeUploadServiceServer struct {
	mock.Mock
}

// mustEmbedUnimplementedUploadServiceServer provides a mock function with given fields:
func (_m *UnsafeUploadServiceServer) mustEmbedUnimplementedUploadServiceServer() {
	_m.Called()
}

// NewUnsafeUploadServiceServer creates a new instance of UnsafeUploadServiceServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUnsafeUploadServiceServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *UnsafeUploadServiceServer {
	mock := &UnsafeUploadServiceServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
