// Code generated by mockery v2.39.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// UnsafeCouponServiceServer is an autogenerated mock type for the UnsafeCouponServiceServer type
type UnsafeCouponServiceServer struct {
	mock.Mock
}

// mustEmbedUnimplementedCouponServiceServer provides a mock function with given fields:
func (_m *UnsafeCouponServiceServer) mustEmbedUnimplementedCouponServiceServer() {
	_m.Called()
}

// NewUnsafeCouponServiceServer creates a new instance of UnsafeCouponServiceServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUnsafeCouponServiceServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *UnsafeCouponServiceServer {
	mock := &UnsafeCouponServiceServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
