// Code generated by mockery v2.39.1. DO NOT EDIT.

package mocks

import (
	upload "trintech/review/dto/storage-management/upload"

	mock "github.com/stretchr/testify/mock"
)

// UploadServiceServer is an autogenerated mock type for the UploadServiceServer type
type UploadServiceServer struct {
	mock.Mock
}

// Upload provides a mock function with given fields: _a0
func (_m *UploadServiceServer) Upload(_a0 upload.UploadService_UploadServer) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Upload")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(upload.UploadService_UploadServer) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mustEmbedUnimplementedUploadServiceServer provides a mock function with given fields:
func (_m *UploadServiceServer) mustEmbedUnimplementedUploadServiceServer() {
	_m.Called()
}

// NewUploadServiceServer creates a new instance of UploadServiceServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUploadServiceServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *UploadServiceServer {
	mock := &UploadServiceServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
