// Code generated by mockery v2.39.1. DO NOT EDIT.

package mocks

import (
	context "context"

	grpc "google.golang.org/grpc"

	mock "github.com/stretchr/testify/mock"

	upload "trintech/review/dto/storage-management/upload"
)

// UploadServiceClient is an autogenerated mock type for the UploadServiceClient type
type UploadServiceClient struct {
	mock.Mock
}

// Upload provides a mock function with given fields: ctx, opts
func (_m *UploadServiceClient) Upload(ctx context.Context, opts ...grpc.CallOption) (upload.UploadService_UploadClient, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Upload")
	}

	var r0 upload.UploadService_UploadClient
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ...grpc.CallOption) (upload.UploadService_UploadClient, error)); ok {
		return rf(ctx, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ...grpc.CallOption) upload.UploadService_UploadClient); ok {
		r0 = rf(ctx, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(upload.UploadService_UploadClient)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewUploadServiceClient creates a new instance of UploadServiceClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUploadServiceClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *UploadServiceClient {
	mock := &UploadServiceClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
