// Code generated by mockery v2.39.1. DO NOT EDIT.

package mocks

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// UploadService is an autogenerated mock type for the UploadService type
type UploadService struct {
	mock.Mock
}

// HandleUploadFiles provides a mock function with given fields: w, r, params
func (_m *UploadService) HandleUploadFiles(w http.ResponseWriter, r *http.Request, params map[string]string) {
	_m.Called(w, r, params)
}

// NewUploadService creates a new instance of UploadService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUploadService(t interface {
	mock.TestingT
	Cleanup(func())
}) *UploadService {
	mock := &UploadService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
