// Code generated by mockery v2.39.1. DO NOT EDIT.

package mocks

import (
	context "context"
	entity "trintech/review/internal/coupon-management/entity"
	database "trintech/review/pkg/database"

	mock "github.com/stretchr/testify/mock"
)

// UsedCouponRepository is an autogenerated mock type for the UsedCouponRepository type
type UsedCouponRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, db, data
func (_m *UsedCouponRepository) Create(ctx context.Context, db database.Executor, data *entity.UsedCoupon) error {
	ret := _m.Called(ctx, db, data)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, database.Executor, *entity.UsedCoupon) error); ok {
		r0 = rf(ctx, db, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ListUsedCouponByUserID provides a mock function with given fields: ctx, db, userID
func (_m *UsedCouponRepository) ListUsedCouponByUserID(ctx context.Context, db database.Executor, userID int64) ([]*entity.CouponUsedCoupon, error) {
	ret := _m.Called(ctx, db, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListUsedCouponByUserID")
	}

	var r0 []*entity.CouponUsedCoupon
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, database.Executor, int64) ([]*entity.CouponUsedCoupon, error)); ok {
		return rf(ctx, db, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, database.Executor, int64) []*entity.CouponUsedCoupon); ok {
		r0 = rf(ctx, db, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.CouponUsedCoupon)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, database.Executor, int64) error); ok {
		r1 = rf(ctx, db, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewUsedCouponRepository creates a new instance of UsedCouponRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUsedCouponRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *UsedCouponRepository {
	mock := &UsedCouponRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
