// Code generated by mockery v2.39.1. DO NOT EDIT.

package mocks

import (
	context "context"
	entity "trintech/review/internal/user-management/entity"

	mock "github.com/stretchr/testify/mock"
)

// UserHistoryRepo is an autogenerated mock type for the UserHistoryRepo type
type UserHistoryRepo struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, data
func (_m *UserHistoryRepo) Create(ctx context.Context, data *entity.UserHistory) (int64, error) {
	ret := _m.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.UserHistory) (int64, error)); ok {
		return rf(ctx, data)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *entity.UserHistory) int64); ok {
		r0 = rf(ctx, data)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *entity.UserHistory) error); ok {
		r1 = rf(ctx, data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewUserHistoryRepo creates a new instance of UserHistoryRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserHistoryRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserHistoryRepo {
	mock := &UserHistoryRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
