// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.14.0
// source: coupon.proto

package coupon

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	CouponService_CreateCoupon_FullMethodName         = "/pb.CouponService/CreateCoupon"
	CouponService_DeleteCouponByID_FullMethodName     = "/pb.CouponService/DeleteCouponByID"
	CouponService_RetrieveCouponByCode_FullMethodName = "/pb.CouponService/RetrieveCouponByCode"
	CouponService_ListUsedCoupon_FullMethodName       = "/pb.CouponService/ListUsedCoupon"
	CouponService_ApplyCoupon_FullMethodName          = "/pb.CouponService/ApplyCoupon"
)

// CouponServiceClient is the client API for CouponService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CouponServiceClient interface {
	CreateCoupon(ctx context.Context, in *CreateCouponRequest, opts ...grpc.CallOption) (*CreateCouponResponse, error)
	DeleteCouponByID(ctx context.Context, in *DeleteCouponByIDRequest, opts ...grpc.CallOption) (*DeleteCouponByIDResponse, error)
	RetrieveCouponByCode(ctx context.Context, in *RetrieveCouponByCodeRequest, opts ...grpc.CallOption) (*RetrieveCouponByCodeResponse, error)
	ListUsedCoupon(ctx context.Context, in *ListUsedCouponRequest, opts ...grpc.CallOption) (*ListUsedCouponResponse, error)
	ApplyCoupon(ctx context.Context, in *ApplyCouponRequest, opts ...grpc.CallOption) (*ApplyCouponResponse, error)
}

type couponServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCouponServiceClient(cc grpc.ClientConnInterface) CouponServiceClient {
	return &couponServiceClient{cc}
}

func (c *couponServiceClient) CreateCoupon(ctx context.Context, in *CreateCouponRequest, opts ...grpc.CallOption) (*CreateCouponResponse, error) {
	out := new(CreateCouponResponse)
	err := c.cc.Invoke(ctx, CouponService_CreateCoupon_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *couponServiceClient) DeleteCouponByID(ctx context.Context, in *DeleteCouponByIDRequest, opts ...grpc.CallOption) (*DeleteCouponByIDResponse, error) {
	out := new(DeleteCouponByIDResponse)
	err := c.cc.Invoke(ctx, CouponService_DeleteCouponByID_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *couponServiceClient) RetrieveCouponByCode(ctx context.Context, in *RetrieveCouponByCodeRequest, opts ...grpc.CallOption) (*RetrieveCouponByCodeResponse, error) {
	out := new(RetrieveCouponByCodeResponse)
	err := c.cc.Invoke(ctx, CouponService_RetrieveCouponByCode_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *couponServiceClient) ListUsedCoupon(ctx context.Context, in *ListUsedCouponRequest, opts ...grpc.CallOption) (*ListUsedCouponResponse, error) {
	out := new(ListUsedCouponResponse)
	err := c.cc.Invoke(ctx, CouponService_ListUsedCoupon_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *couponServiceClient) ApplyCoupon(ctx context.Context, in *ApplyCouponRequest, opts ...grpc.CallOption) (*ApplyCouponResponse, error) {
	out := new(ApplyCouponResponse)
	err := c.cc.Invoke(ctx, CouponService_ApplyCoupon_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CouponServiceServer is the server API for CouponService service.
// All implementations must embed UnimplementedCouponServiceServer
// for forward compatibility
type CouponServiceServer interface {
	CreateCoupon(context.Context, *CreateCouponRequest) (*CreateCouponResponse, error)
	DeleteCouponByID(context.Context, *DeleteCouponByIDRequest) (*DeleteCouponByIDResponse, error)
	RetrieveCouponByCode(context.Context, *RetrieveCouponByCodeRequest) (*RetrieveCouponByCodeResponse, error)
	ListUsedCoupon(context.Context, *ListUsedCouponRequest) (*ListUsedCouponResponse, error)
	ApplyCoupon(context.Context, *ApplyCouponRequest) (*ApplyCouponResponse, error)
	mustEmbedUnimplementedCouponServiceServer()
}

// UnimplementedCouponServiceServer must be embedded to have forward compatible implementations.
type UnimplementedCouponServiceServer struct {
}

func (UnimplementedCouponServiceServer) CreateCoupon(context.Context, *CreateCouponRequest) (*CreateCouponResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCoupon not implemented")
}
func (UnimplementedCouponServiceServer) DeleteCouponByID(context.Context, *DeleteCouponByIDRequest) (*DeleteCouponByIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteCouponByID not implemented")
}
func (UnimplementedCouponServiceServer) RetrieveCouponByCode(context.Context, *RetrieveCouponByCodeRequest) (*RetrieveCouponByCodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RetrieveCouponByCode not implemented")
}
func (UnimplementedCouponServiceServer) ListUsedCoupon(context.Context, *ListUsedCouponRequest) (*ListUsedCouponResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListUsedCoupon not implemented")
}
func (UnimplementedCouponServiceServer) ApplyCoupon(context.Context, *ApplyCouponRequest) (*ApplyCouponResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ApplyCoupon not implemented")
}
func (UnimplementedCouponServiceServer) mustEmbedUnimplementedCouponServiceServer() {}

// UnsafeCouponServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CouponServiceServer will
// result in compilation errors.
type UnsafeCouponServiceServer interface {
	mustEmbedUnimplementedCouponServiceServer()
}

func RegisterCouponServiceServer(s grpc.ServiceRegistrar, srv CouponServiceServer) {
	s.RegisterService(&CouponService_ServiceDesc, srv)
}

func _CouponService_CreateCoupon_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCouponRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CouponServiceServer).CreateCoupon(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CouponService_CreateCoupon_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CouponServiceServer).CreateCoupon(ctx, req.(*CreateCouponRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CouponService_DeleteCouponByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCouponByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CouponServiceServer).DeleteCouponByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CouponService_DeleteCouponByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CouponServiceServer).DeleteCouponByID(ctx, req.(*DeleteCouponByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CouponService_RetrieveCouponByCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetrieveCouponByCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CouponServiceServer).RetrieveCouponByCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CouponService_RetrieveCouponByCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CouponServiceServer).RetrieveCouponByCode(ctx, req.(*RetrieveCouponByCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CouponService_ListUsedCoupon_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUsedCouponRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CouponServiceServer).ListUsedCoupon(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CouponService_ListUsedCoupon_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CouponServiceServer).ListUsedCoupon(ctx, req.(*ListUsedCouponRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CouponService_ApplyCoupon_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyCouponRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CouponServiceServer).ApplyCoupon(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CouponService_ApplyCoupon_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CouponServiceServer).ApplyCoupon(ctx, req.(*ApplyCouponRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CouponService_ServiceDesc is the grpc.ServiceDesc for CouponService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CouponService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.CouponService",
	HandlerType: (*CouponServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateCoupon",
			Handler:    _CouponService_CreateCoupon_Handler,
		},
		{
			MethodName: "DeleteCouponByID",
			Handler:    _CouponService_DeleteCouponByID_Handler,
		},
		{
			MethodName: "RetrieveCouponByCode",
			Handler:    _CouponService_RetrieveCouponByCode_Handler,
		},
		{
			MethodName: "ListUsedCoupon",
			Handler:    _CouponService_ListUsedCoupon_Handler,
		},
		{
			MethodName: "ApplyCoupon",
			Handler:    _CouponService_ApplyCoupon_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "coupon.proto",
}
