/* *
                      _
  ___   _   _   ___  | |_    ___    _ __ ___
 / __| | | | | / __| | __|  / _ \  | '_ ` _ \
| (__  | |_| | \__ \ | |_  | (_) | | | | | | |
 \___|  \__,_| |___/  \__|  \___/  |_| |_| |_|

*/
// * Code generated by protoc-gen-custom. DO NOT EDIT.
// * versions:
// * - protoc-gen-custom (devel)
// * - protoc                   v3.14.0
// * source: pb

package coupon

const (
	CouponService_CreateCoupon         = "/pb.CouponService/CreateCoupon"
	CouponService_DeleteCouponByID     = "/pb.CouponService/DeleteCouponByID"
	CouponService_RetrieveCouponByCode = "/pb.CouponService/RetrieveCouponByCode"
	CouponService_ListUsedCoupon       = "/pb.CouponService/ListUsedCoupon"
	CouponService_ApplyCoupon          = "/pb.CouponService/ApplyCoupon"
)
