/*
                       _
   ___   _   _   ___  | |_    ___    _ __ ___
  / __| | | | | / __| | __|  / _ \  | '_ ` _ \
 | (__  | |_| | \__ \ | |_  | (_) | | | | | | |
  \___|  \__,_| |___/  \__|  \___/  |_| |_| |_|

*/
// * Code generated by protoc-gen-custom. DO NOT EDIT.
// * versions:
// * - protoc-gen-custom (devel)
// * - protoc                   v3.14.0
// * source: pb

package coupon

func (x CouponType) FromString(str string) CouponType {
	switch str {
	case CouponType_CouponType_NONE.String():
		return CouponType_CouponType_NONE
	case CouponType_CouponType_USER.String():
		return CouponType_CouponType_USER
	case CouponType_CouponType_PRODUCT.String():
		return CouponType_CouponType_PRODUCT
	}
	return CouponType(0)
}
